### ISSUE TITLE
Remove this Ionic 2 tutorial

### ISSUE THREAD

**Issue by luchillo17** [pluralsight/guides#155]
I made this tutorial but with the recent `Ionic 2.0-RC.0` all this database versioning goes to hell, now it doesn't work any more, so i suggest we delete the tutorial since it doesn't even work any more.

https://github.com/pluralsight/guides/blob/master/published/software-engineering-best-practices/ionic-2-database-management-and-versioning/article.md

**Comment by prtkgpt** [comment]
@Luchillo would you like to update this tutorial showcasing recent Ionic updates.

**Comment by luchillo17** [comment]
At first i tough it was worth crap since Ionic completely removed the api that i was using in it, i almost had to rewrite one of my company's app from scratch, then i realized i just have to provide that same api, and it turned up to be easier than i tough, i'll try to update it this weekend.

**Comment by prtkgpt** [comment]
Thanks @Luchillo
