### ISSUE TITLE
Grammatical error in `Everything you need to know about JSON`.

### ISSUE THREAD

**Issue by carlsmith** [pluralsight/guides#185]
In the article *Everything you need to know about JSON*, in the first paragraph of the section named *The Rules*, there's the following sentence:

*The values contained by objects and arrays, must also be JSON serialisable.*

The comma should not be there.

**Comment by carlsmith** [comment]
Just realised I can fix it myself. Sorry for the noise.

**Comment by durden** [comment]
@carlsmith No worries, thanks for the cleanup!
