### ISSUE TITLE
Punctuation should be outside of grave accents when using Markdown

### ISSUE THREAD

**Issue by carlsmith** [pluralsight/guides#189]
I just revisited one of the docs I wrote, and found that it had been edited, and that punctuation had been added to inline code samples. I understand that most people follow the convention of placing punctuation inside quotes, even though the punctuation is not part of the quote. For example:

    He said "hello," but no one heard.

However, adding punctuation to code samples is incorrect and corrupts the code in the sample. For example, this would be wrong:

    There is a helper named `foo,` though not in early versions.

The correct markup would be...

    There is a helper named `foo`, though not in early versions.

Code samples are only *marked up* with grave accents; there are no actual quotes in the rendered document. Adding punctuation to code samples also introduces syntax errors in that code.

I've fixed this issue in my tutorials, but it's presumably not isolated to just those two.

**Comment by carlsmith** [comment]
Having looked through over a dozen of the most recently published tutorials, as well as another dozen tutorials that were published about the same time as mine were, it appears that this issue was only introduced to the two tutorials that I wrote. They've both been fixed, so it seems safe to close this issue.

**Comment by durden** [comment]
Thanks for looking into it!!
