### ISSUE TITLE
how to host node js alexa project on local server(public IP) 

### ISSUE THREAD

**Issue by shishirc** [pluralsight/guides#290]
I am trying to host this node JS code on local server , but not getting success.

could you please help me on the same

**Comment by durden** [comment]
Which node JS code/guide are you referring to?

**Comment by shishirc** [comment]
I got success on this, I have hosted alexa-app-server package  on my local machine.
one more thing no need to use any alexa-specific devolvement kit. One can call alexa-skill/device from any HTTPS web-service. only need to take care of input/output JSON format.
